---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lil-eks
  region: us-west-2
  tags:
    lil-eks: lil-eks

nodeGroups:
  - name: worker-node
    instanceType: m5.large
    desiredCapacity: 3

  